In [3]:
import numpy as np

In [4]:
arr = [1,2,3,4,5,6,7,8,9]
new = []
for i in arr:
    new.append(i+10)
new

[11, 12, 13, 14, 15, 16, 17, 18, 19]

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

In [9]:
arr.ndim

1

In [10]:
arr1.shape

(2, 5)

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
matrix = np.random.randint(20,50, size=(10,10))

In [15]:
print(matrix)

[[43 35 26 24 40 43 40 25 33 26]
 [41 45 31 20 24 47 33 20 25 26]
 [29 35 22 28 25 30 26 46 49 49]
 [43 33 48 23 35 47 23 21 40 34]
 [42 21 28 43 22 33 47 27 29 37]
 [45 26 37 48 40 31 32 28 27 21]
 [31 35 41 42 29 29 24 25 40 32]
 [47 22 26 39 37 39 27 22 32 38]
 [40 36 31 20 28 34 45 28 38 29]
 [27 22 37 30 49 47 41 46 24 46]]


In [16]:
matrix > 41

array([[ True, False, False, False, False,  True, False, False, False,
        False],
       [False,  True, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [ True, False,  True, False, False,  True, False, False, False,
        False],
       [ True, False, False,  True, False, False,  True, False, False,
        False],
       [ True, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False,  True,  True, False,  True, False,
         True]])

In [17]:
matrix[matrix > 41]

array([43, 43, 45, 47, 46, 49, 49, 43, 48, 47, 42, 43, 47, 45, 48, 42, 47,
       45, 49, 47, 46, 46], dtype=int32)

In [18]:
arr4 = np.array([1,2,3,4,5,6])

In [19]:
arr4[[0,2,4]]

array([1, 3, 5])

In [20]:
new = np.arange(12)
print(new)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
new.reshape((2,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## solving system of linear equations

In [22]:
A = np.array([
    [2,1,-1],
    [-3,-1,2],
    [-2,1,2]
])

B = np.array([8,-11,-3])

solution = np.linalg.solve(A,B)

a = np.array([1,2,3])
b = np.array([[3],[2],[1]])
a @ b

array([10])

In [23]:
print(solution)

[ 2.  3. -1.]


## roation of a coordinate using numpy

In [24]:
p = np.array([3,2])

In [25]:
theta = np.radians(45)
print(type(theta))

<class 'numpy.float64'>


In [32]:
rotation = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])


In [33]:
new_coordinate = rotation @ p

In [34]:
new_coordinate

array([0.70710678, 3.53553391])